# Generated by Django 4.1.13 on 2024-05-25 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0208_merge_acunetix'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngEvaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_point', models.IntegerField(blank=True, help_text='Points for critical findings', null=True, verbose_name='Critical Point')),
                ('high_point', models.IntegerField(blank=True, help_text='Points for high findings', null=True, verbose_name='High Point')),
                ('medium_point', models.IntegerField(blank=True, help_text='Points for medium findings', null=True, verbose_name='Medium Point')),
                ('low_point', models.IntegerField(blank=True, help_text='Points for low findings', null=True, verbose_name='Low Point')),
                ('initial_points', models.IntegerField(blank=True, help_text='Initial points for the engagement', null=True, verbose_name='Initial Points')),
            ],
            options={
                'verbose_name': 'Engagement Evaluation',
                'verbose_name_plural': 'Engagement Evaluations',
            },
        ),
        migrations.AddField(
            model_name='engagement',
            name='eng_evaluate',
            field=models.OneToOneField(blank=True, help_text='Evaluation details of the engagement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.engevaluate'),
        ),
    ]
