# Generated by Django 4.1.13 on 2024-05-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0211_engagementevaluate_remove_engagement_eng_evaluate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement_Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the engagement evaluation', max_length=255, null=True, unique=True, verbose_name='Name')),
                ('critical_point', models.IntegerField(blank=True, help_text='Points for critical findings', null=True, verbose_name='Critical Point')),
                ('high_point', models.IntegerField(blank=True, help_text='Points for high findings', null=True, verbose_name='High Point')),
                ('medium_point', models.IntegerField(blank=True, help_text='Points for medium findings', null=True, verbose_name='Medium Point')),
                ('low_point', models.IntegerField(blank=True, help_text='Points for low findings', null=True, verbose_name='Low Point')),
                ('threshold', models.IntegerField(blank=True, help_text='Threshold for the engagement', null=True, verbose_name='Threshold')),
            ],
            options={
                'verbose_name': 'Engagement Evaluation',
                'verbose_name_plural': 'Engagement Evaluations',
            },
        ),
        migrations.AlterField(
            model_name='engagement',
            name='engagement_evaluate',
            field=models.OneToOneField(blank=True, help_text='Evaluation details of the engagement', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dojo.engagement_evaluate'),
        ),
        migrations.DeleteModel(
            name='EngagementEvaluate',
        ),
    ]
