# Generated by Django 4.1.13 on 2024-05-25 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0212_engagement_evaluate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement_evaluate',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='engagement_evaluate',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dojo.product'),
            preserve_default=False,
        ),
    ]
